name: "full-icu"
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-20.04, macos-latest]
        node: [11, 12, 12.0.0, 12.13.1, 13, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i icu4c-data@64l
      - run: node --version
      - name: node ${{ matrix.node }}
        run: node ./.github/actions/index/index.js
        env:
          NODE_ICU_DATA: node_modules/full-icu
      - name: node ${{ matrix.node }} btest402
        run: node ./.github/actions/btest402/btest402.js
        env:
          NODE_ICU_DATA: node_modules/full-icu

      - run: echo $NODE_ICU_DATA
        env:
          NODE_ICU_DATA: ${{ github.workspace }}/node_modules/icu4c-data
      - name: organic
        uses: ./.github/actions/index
        env:
          NODE_ICU_DATA: "${{ github.workspace }}/node_modules/icu4c-data"
      - name: organic btest402
        uses: ./.github/actions/btest402
        env:
          NODE_ICU_DATA: "${{ github.workspace }}/node_modules/icu4c-data"
      - name: organic2
        uses: ./.github/actions/index
        env:
          NODE_ICU_DATA: node_modules/icu4c-data
      - name: organic2
        uses: ./.github/actions/index
        env:
          NODE_ICU_DATA: ./node_modules/icu4c-data
