name: "node icu test"
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [11, 12, 13, 14]
    steps:
      - uses: actions/checkout@v2
      - run: node index.js
        name: organic
      - name: organic btest402
        run: node btest402.js
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      - run: node index.js
        name: node ${{ matrix.node }}
      - name: node ${{ matrix.node }} btest402
        run: node btest402.js
